version: '3'

services:
  postgresql:
    container_name: postgresql
    image: postgis/postgis:13-3.1-alpine
    restart: always
    volumes:
      - /pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}